[phases.setup]
nixPkgs = ["nodejs_22", "pnpm", "caddy"]

[phases.install]
cmds = ["pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["pnpm run build"]

[start]
cmd = "caddy run --config /assets/Caddyfile --adapter caddyfile"

