# Tell Railway how to build the client service

[phases.setup]
nixPkgs = ["nodejs_22", "pnpm"]

[phases.install]
cmd = "pnpm install --no-frozen-lockfile --force"

[phases.build]
cmd = "pnpm run build"

[start]
cmd = "pnpm run preview -- --host 0.0.0.0 --port 8080"
