[phases.setup]
nixPkgs = ["nodejs_22", "pnpm"]

[phases.install]
cmds = [
  "pnpm install --no-frozen-lockfile"
]

[phases.build]
cmds = [
  "pnpm --filter client... run build",
  "pnpm --filter @realenhance/server run build"
]

[start]
cmd = "pnpm --filter @realenhance/server run start"

# Prevent Nixpacks from copying node_modules from the host
[variables]
NIXPACKS_SKIP_NODE_MODULES_COPY = "true"
