[phases.setup]
nixPkgs = ["nodejs_18", "pnpm"]

[phases.install]
cmds = [
  "pnpm install --no-frozen-lockfile"
]

[phases.build]
cmds = [
  "pnpm --filter ./client... run build",
  "pnpm --filter @realenhance/server run build"
]

[start]
cmd = "pnpm --filter @realenhance/server run start"
