# .nixpacks.toml
# This file MUST live in the root of the repo (same level as package.json)

[phases.setup]
# Force a modern Node + pnpm via Nix. If nodejs_22 fails in your project,
# change it to nodejs_20.
nixPkgs = ["nodejs_20", "pnpm"]

[phases.install]
# IMPORTANT: no --frozen-lockfile
cmds = [
  "pnpm install --no-frozen-lockfile"
]

[phases.build]
# Build the React app first so client/dist exists,
# then compile the server
cmds = [
  "pnpm --filter client build",
  "pnpm --filter @realenhance/server build"
]

[start]
# Boot the API/server (which will also serve client/dist)
cmd = "pnpm --filter @realenhance/server start"

[variables]
PORT = "8080"
NODE_ENV = "production"
