export default function TermsPage() {
  return (
    <div className="bg-slate-50">
      <div className="mx-auto w-full max-w-4xl px-4 py-10 sm:px-6 lg:px-8 lg:py-12">
        <article className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm sm:p-8 lg:p-10">
          <header className="mb-8 space-y-2">
            <h1 className="text-3xl font-bold tracking-tight text-slate-900 sm:text-4xl">RealEnhance Terms of Service (Draft)</h1>
            <p className="text-sm text-slate-600">Effective Date: [Insert Date]</p>
            <p className="text-slate-700">
              Welcome to RealEnhance. These Terms of Service ("Terms") govern your use of the RealEnhance website,
              applications, and services (collectively, the "Service").
            </p>
            <p className="text-slate-700">By creating an account or using the Service, you agree to these Terms.</p>
            <p className="text-slate-700">If you do not agree to these Terms, you must not use the Service.</p>
          </header>

          <div className="space-y-8 text-slate-700">
            <section className="space-y-3">
              <h2 className="text-xl font-semibold text-slate-900">1. About RealEnhance</h2>
              <p>
                RealEnhance provides automated image enhancement, decluttering, and virtual staging tools designed
                primarily for property marketing.
              </p>
              <p>
                The Service processes images uploaded by users and generates enhanced or staged images using automated
                systems.
              </p>
              <p>
                RealEnhance provides tools only and does not verify the accuracy or authenticity of any images
                generated or uploaded.
              </p>
            </section>

            <section className="space-y-3">
              <h2 className="text-xl font-semibold text-slate-900">2. User Responsibility for Image Accuracy</h2>
              <p>
                Users are solely responsible for reviewing and verifying that any images generated, enhanced, or
                modified using the Service accurately represent the property before they are used in advertising,
                listings, or marketing.
              </p>
              <p>
                RealEnhance does not guarantee that generated images accurately represent the physical property and
                accepts no responsibility for any reliance placed on generated images.
              </p>
              <p>
                Users must ensure that their use of images complies with all applicable laws, regulations, and
                industry standards governing property marketing and advertising.
              </p>
            </section>

            <section className="space-y-3">
              <h2 className="text-xl font-semibold text-slate-900">3. Virtual Staging Disclosure</h2>
              <p>
                Where required by law, regulation, or professional guidelines, users must clearly disclose that images
                have been digitally enhanced or virtually staged.
              </p>
              <p>
                RealEnhance accepts no responsibility for how images are presented or disclosed once downloaded or
                published by users.
              </p>
            </section>

            <section className="space-y-3">
              <h2 className="text-xl font-semibold text-slate-900">4. User Content</h2>
              <p>Users retain ownership of any images they upload to the Service.</p>
              <p>By uploading images, users confirm that:</p>
              <ul className="list-disc space-y-2 pl-6">
                <li>they have the legal right to upload and process the images</li>
                <li>the images do not infringe any copyright, privacy, or other rights</li>
                <li>the images do not contain unlawful content</li>
              </ul>
              <p>Users grant RealEnhance a limited licence to process images solely for the purpose of providing the Service.</p>
            </section>

            <section className="space-y-3">
              <h2 className="text-xl font-semibold text-slate-900">5. AI-Generated Output</h2>
              <p>
                Outputs generated by RealEnhance are produced automatically by machine learning and image processing
                systems.
              </p>
              <p>
                Generated images may contain inaccuracies, visual artefacts, or alterations that do not reflect the
                physical property.
              </p>
              <p>Users must independently verify all outputs before use.</p>
            </section>

            <section className="space-y-3">
              <h2 className="text-xl font-semibold text-slate-900">6. Acceptable Use</h2>
              <p>Users agree not to use the Service:</p>
              <ul className="list-disc space-y-2 pl-6">
                <li>to create misleading or deceptive marketing materials</li>
                <li>to alter images in a way that misrepresents property structure or features</li>
                <li>to violate any real estate advertising regulations</li>
                <li>to upload unlawful, harmful, or infringing content</li>
                <li>to attempt to disrupt or reverse engineer the Service</li>
              </ul>
              <p>RealEnhance may suspend or terminate accounts that violate these rules.</p>
            </section>

            <section className="space-y-3">
              <h2 className="text-xl font-semibold text-slate-900">7. Subscriptions and Billing</h2>
              <p>Some features of the Service require a paid subscription.</p>
              <p>Subscription plans may include image usage limits and billing cycles.</p>
              <p>By subscribing, you agree to pay the applicable fees associated with your chosen plan.</p>
              <p>Unless cancelled before renewal, subscriptions automatically renew each billing period.</p>
            </section>

            <section className="space-y-3">
              <h2 className="text-xl font-semibold text-slate-900">8. Service Availability</h2>
              <p>RealEnhance strives to maintain reliable service but does not guarantee uninterrupted availability.</p>
              <p>
                The Service may be modified, updated, or temporarily unavailable due to maintenance or technical
                issues.
              </p>
            </section>

            <section className="space-y-3">
              <h2 className="text-xl font-semibold text-slate-900">9. Limitation of Liability</h2>
              <p>
                To the maximum extent permitted by law, RealEnhance shall not be liable for any indirect, incidental,
                consequential, or special damages arising from the use of the Service.
              </p>
              <p>This includes, but is not limited to:</p>
              <ul className="list-disc space-y-2 pl-6">
                <li>loss of business</li>
                <li>loss of revenue</li>
                <li>loss of data</li>
                <li>reliance on generated images</li>
              </ul>
              <p>
                The total liability of RealEnhance for any claim shall not exceed the amount paid by the user for the
                Service during the preceding 12 months.
              </p>
            </section>

            <section className="space-y-3">
              <h2 className="text-xl font-semibold text-slate-900">10. Indemnity</h2>
              <p>
                Users agree to indemnify and hold harmless RealEnhance and its operators from any claims, damages,
                liabilities, or expenses arising from:
              </p>
              <ul className="list-disc space-y-2 pl-6">
                <li>the user’s use of generated images</li>
                <li>property marketing materials created using the Service</li>
                <li>violation of these Terms or applicable laws.</li>
              </ul>
            </section>

            <section className="space-y-3">
              <h2 className="text-xl font-semibold text-slate-900">11. Termination</h2>
              <p>RealEnhance may suspend or terminate accounts that violate these Terms or misuse the Service.</p>
              <p>Users may cancel their account at any time.</p>
            </section>

            <section className="space-y-3">
              <h2 className="text-xl font-semibold text-slate-900">12. Changes to Terms</h2>
              <p>RealEnhance may update these Terms from time to time.</p>
              <p>Continued use of the Service after changes constitutes acceptance of the revised Terms.</p>
            </section>

            <section className="space-y-3">
              <h2 className="text-xl font-semibold text-slate-900">13. Governing Law</h2>
              <p>These Terms are governed by the laws of New Zealand.</p>
              <p>
                Any disputes arising from these Terms will be subject to the jurisdiction of the courts of New Zealand.
              </p>
            </section>
          </div>
        </article>
      </div>
    </div>
  );
}
